### ISSUE TITLE
Close/reset element on popup and input is broken

### ISSUE THREAD

**Issue by basvasilich** [yandex-ui/stylobate-islands#75]
Looks like because of the rules order and `background: 50% no-repeat;` rule after.

I have this in my code: 

``` css

._nb-popup-close,
._nb-simple-input ._nb-input-reset,
._nb-complex-input ._nb-input-reset,
._nb-small-complex-input ._nb-input-reset,
._nb-large-complex-input ._nb-input-reset,
._nb-small-simple-input ._nb-input-reset,
._nb-large-simple-input ._nb-input-reset {
  width: 16px;
  height: 16px;
  background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiI+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik04IDEuMjA5Yy0zLjc1MSAwLTYuNzkxIDMuMDQtNi43OTEgNi43OTEgMCAzLjc0OSAzLjA0IDYuNzg5IDYuNzkxIDYuNzg5IDMuNzQ5IDAgNi43ODktMy4wNCA2Ljc4OS02Ljc4OSAwLTMuNzUxLTMuMDQtNi43OTEtNi43ODktNi43OTF6bTMuOTkgOS4zNTVsLTEuNDI2IDEuNDI2LTIuNTY0LTIuNTY0LTIuNTY0IDIuNTY0LTEuNDI2LTEuNDI2IDIuNTY0LTIuNTY0LTIuNTY0LTIuNTY0IDEuNDI2LTEuNDI2IDIuNTY0IDIuNTY0IDIuNTY0LTIuNTY0IDEuNDI2IDEuNDI2LTIuNTY0IDIuNTY0IDIuNTY0IDIuNTY0eiIvPjwvc3ZnPg==");
}
._nb-popup-close,
._nb-simple-input ._nb-input-reset,
._nb-complex-input ._nb-input-reset,
._nb-small-complex-input ._nb-input-reset,
._nb-large-complex-input ._nb-input-reset,
._nb-small-simple-input ._nb-input-reset,
._nb-large-simple-input ._nb-input-reset,
.nb-select ._nb-button-content:before,
.nb-select-dropdown ._nb-select-group-item > ._nb-select-a:before,
._nb-small-select ._nb-button-content:before,
._nb-small-select-dropdown ._nb-select-group-item > ._nb-select-a:before,
.is-selected ._nb-select-a:after,
._nb-checkbox-radio-flag,
._nb-checkbox-normal-flag,
.nb-icon {
  position: relative;
  display: inline-block;
  vertical-align: middle;
  margin-top: -0.2em;
  background: 50% no-repeat;
}

```
